apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 3
agents: 4
image: docker.io/rancher/k3s:v1.22.7-k3s1
ports:
  - port: 80:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  #- port: 8080:8080 # same as `--port '8080:80@loadbalancer'`
  #  nodeFilters:
  #    - loadbalancer