---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kuberentes.io/name: petclinic
    helm.sh/chart: petclinic-0.1.0
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/managed-by: Helm
  name: petclinic-env
data:
  # env variables
  SPRING_PROFILES_ACTIVE: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app.kubernetes.io/name: petclinic
    helm.sh/chart: petclinic-0.1.0
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 8080
      protocol: TCP
      port: 80
  selector:
    app.kubernetes.io/name: petclinic
    app.kubernetes.io/instance: petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app.kubernetes.io/name: petclinic
    helm.sh/chart: petclinic-0.1.0
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/instance: petclinic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: petclinic
        app.kubernetes.io/instance: petclinic
    spec:
      containers:
        - name: petclinic
          image: "arey/springboot-petclinic:latest"
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: petclinic-env
                  key: SPRING_PROFILES_ACTIVE
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic
  labels:
    app.kubernetes.io/name: petclinic
    helm.sh/chart: petclinic-0.1.0
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: petclinic
              port: 
                number: 80