apiVersion: v1
kind: Service
metadata:
  name: {{ include "task1.fullname" . }}
  labels:
    {{- include "task1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port, $portValue := .Values.service.ports }}
    - name: {{ $port }}
      targetPort: {{ $portValue.targetPort }}
      protocol: {{ $portValue.protocol }}
      port: {{ $portValue.port }}
  {{- end }}
  selector:
    {{- include "task1.selectorLabels" . | nindent 4 }}
